import { Injectable } from "@angular/core";
import { Portfolio } from "./portfolio";

@Injectable({
    providedIn: 'root'
})
export class PortfolioService {
    
    retrieveAll(): Portfolio[] {
        return SKILLS;
    }

    //retrieveById(id: number): Portfolio {
        //return SKILLS.find((skillItereator: Portfolio) => skillItereator.id === id);
    //}
}

var SKILLS: Portfolio[] = [
    {
        id: 1,
        name: 'Angular: CLI ',
        releaseDate: 'November 2, 2019',
        description: 'Neste curso, os alunos irão obter um grande conhecimento nos principais recursos do CLI.',
        duration: 120,
        code: 'XLF-1212',
        rating: 3,
        price:  12.99,
        imageUrl: '/assets/images/cli.png',
    },
    {
        id: 2,
        name: 'Angular: Forms',
        releaseDate: 'November 4, 2019',
        description: 'Neste curso, os alunos irão obter um conhecimento aprofundado sobre os recursos disponíveis no módulo de Forms.',
        duration: 80,
        code: 'DWQ-3412',
        rating: 3.5,
        price: 24.99,
        imageUrl: '/assets/images/forms.png',
    },
    {
        id: 3,
        name: 'Angular: HTTP',
        releaseDate: 'November 8, 2019',
        description: 'Neste curso, os alunos irão obter um conhecimento aprofundado sobre os recursos disponíveis no módulo de HTTP.',
        duration: 80,
        code: 'QPL-0913',
        rating: 4.0,
        price: 36.99,
        imageUrl: '/assets/images/http.png',
    },
    {
        id: 4,
        name: 'Angular: Router',
        releaseDate: 'November 16, 2019',
        description: 'Neste curso, os alunos irão obter um conhecimento aprofundado sobre os recursos disponíveis no módulo de Router.',
        duration: 80,
        code: 'OHP-1095',
        rating: 4.5,
        price: 46.99,
        imageUrl: '/assets/images/router.png',
    },
    {
        id: 5,
        name: 'Angular: Animations',
        releaseDate: 'November 25, 2019',
        description: 'Neste curso, os alunos irão obter um conhecimento aprofundado sobre os recursos disponíveis sobre Animation.',
        duration: 80,
        code: 'PWY-9381',
        rating: 5,
        price: 56.99,
        imageUrl: '/assets/images/animations.png',
    },
    {
        id: 6,
        name: 'HTML',
        releaseDate: 'November 25, 2019',
        description: '',
        duration: 80,
        code: 'PWY-9381',
        rating: 5,
        price: 56.99,
        imageUrl: '/assets/images/html.png',
    },
    {
        id: 7,
        name: 'Css-3',
        releaseDate: 'November 25, 2019',
        description: '',
        duration: 80,
        code: 'PWY-9381',
        rating: 5,
        price: 56.99,
        imageUrl: '/assets/images/css.png',
    },
    {
        id: 8,
        name: 'Javascript',
        releaseDate: 'November 25, 2019',
        description: 'Javascript',
        duration: 80,
        code: 'PWY-9381',
        rating: 5,
        price: 56.99,
        imageUrl: '/assets/images/js.png',
    },
    {
        id: 9,
        name: 'Typescript',
        releaseDate: 'November 25, 2019',
        description: 'Typescript',
        duration: 80,
        code: 'PWY-9381',
        rating: 5,
        price: 56.99,
        imageUrl: '/assets/images/typescript.png',
    },
    {
        id: 10,
        name: 'Python',
        releaseDate: 'November 25, 2019',
        description: 'Python',
        duration: 80,
        code: 'PWY-9381',
        rating: 5,
        price: 56.99,
        imageUrl: '/assets/images/python.png',
    },
    {
        id: 11,
        name: 'Banco de Dados',
        releaseDate: 'November 25, 2019',
        description: 'Banco de Dados',
        duration: 80,
        code: 'PWY-9381',
        rating: 5,
        price: 56.99,
        imageUrl: '/assets/images/data.png',
    },
    {
        id: 12,
        name: 'Dashboards',
        releaseDate: 'November 25, 2019',
        description: 'Dashboards',
        duration: 80,
        code: 'PWY-9381',
        rating: 5,
        price: 56.99,
        imageUrl: '/assets/images/monitor.png',
    },
    {
        id: 13,
        name: 'Business Inteligence',
        releaseDate: 'November 25, 2019',
        description: 'Dashboards',
        duration: 80,
        code: 'PWY-9381',
        rating: 5,
        price: 56.99,
        imageUrl: '/assets/images/bi.png',
    },
    {
        id: 14,
        name: 'Bootstrap',
        releaseDate: 'November 25, 2019',
        description: 'Dashboards',
        duration: 80,
        code: 'PWY-9381',
        rating: 5,
        price: 56.99,
        imageUrl: '/assets/images/bootstrap.png',
    },
    {
        id: 15,
        name: 'Cloud Computing',
        releaseDate: 'November 25, 2019',
        description: 'Dashboards',
        duration: 80,
        code: 'PWY-9381',
        rating: 5,
        price: 56.99,
        imageUrl: '/assets/images/cloud-computing.png',
    }
]
